# Generated by Django 5.0.3 on 2024-05-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('baner', models.ImageField(upload_to='image_category')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('restriction', models.IntegerField()),
                ('construction', models.IntegerField()),
                ('baner', models.ImageField(upload_to='image_movies')),
                ('image', models.ImageField(upload_to='image_details')),
                ('video', models.FileField(upload_to='movies')),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='movie_category', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seryal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('restriction', models.IntegerField()),
                ('construction', models.IntegerField()),
                ('baner', models.ImageField(upload_to='image_movies')),
                ('image', models.ImageField(upload_to='image_details')),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='seryal_category', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='PartSeryal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='part_seryals')),
                ('seryal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_seryal', to='content.seryal')),
            ],
        ),
    ]
