const MovieSlider = [
   {
      title: "A Space Odyssey",
      des: "پس از کشف جسمی عجیب در زیر سطح ماه، بشریت به کمک اَبر رایانه‌ی هوشمند HAL 9000 سعی می‌کند تا از ماهیتش سر دربیاورد.",
      image: "/images/posters/A-SpaceOdyssey.jpeg",
      Ages: "PG",
      imdb: "8.3",
      like: "84",
      bacImg: "/images/HeroSlider/a-space-odyssey.jpg",
   },
   {
      title: "Barry Lyndon",
      des: "ایرلند، قرن هجدهم. کنتس ثروتمند انگلیسی، «لیدی لیندون»، نظر مرد جوان ایرلندی، «بری» را به خود جلب می کند. پس از مرگ شوهر «لیدی لیندون» این دو ازدواج می کنند و «بری» به طبقه ی اشراف راه می یابد.",
      image: "/images/posters/barry-lyndon.jpg",
      Ages: "PG",
      imdb: "8.1",
      like: "89",
      bacImg: "/images/HeroSlider/barry-lyndon.jpeg",
   },
   {
      title: "Three Colors: Red",
      des: "آخرین قسمت از سه‌گانه فیلم‌هایی در مورد مشغله‌های جامعه فرانسوی، اینبار داستان در مورد یک مدل است که در میابد همسایه‌اش از تجاوز به حریم خصوصی مردم لذت می برد.",
      image: "/images/posters/Three-Colours-Red.jpeg",
      Ages: "R",
      imdb: "8.1",
      like: "100",
      bacImg: "/images/HeroSlider/three-colors-red.jpg",
   },
   {
      title: "Oppenheimer",
      des: "زندگی‌نامه دانشمندی آمریکایی به نام جی رابرت اوپنهایمر و تاثیرش در ساخت بمب اتم که...",
      image: "/images/posters/oppenheimer.jpg",
      Ages: "R",
      imdb: "8.3",
      like: "89",
      bacImg: "/images/HeroSlider/oppenheimer.jpg",
   },
   {
      title: "Memento",
      des: "لئونارد مردی که حافظه کوتاه مدتش را از دست داده و دیگر قادر نیست چیز جدیدی را به خاطراتش اضافه کند. او بوسیله یادداشت‌ها و خالکوبی‌ کردن بدنش، به دنبال مردی است که فکر می کند همسرش را به قتل رسانده. در واقع این هدف آخرین چیزی است که او به یاد می آورد.",
      image: "/images/posters/memento.jpg",
      Ages: "R",
      imdb: "8.4",
      like: "83",
      bacImg: "/images/HeroSlider/memento.jpg",
   },
   {
      title: "Better Call Saul",
      des: "سریال بهتره با ساول تماس بگیری اسپین‌آف سریال بریکینگ بد می باشد که داستانش در مورد وکیل والتر وایت، ساول گودمن و دفتر وکالت او و نحوه آشنایی او با اعضای گروه درست قبل از رخ دادن اتفاقات بریکینگ بد می باشد…",
      image: "/images/posters/BetterCallSaul.jpg",
      Ages: "TV-MA",
      imdb: "9",
      like: "98",
      bacImg: "/images/HeroSlider/BetterCallSaul.jpeg",
   },
   {
      title: "The Walking Dead",
      des: "سریال بهتره با ساول تماس بگیری اسپین‌آف سریال بریکینگ بد می باشد که داستانش در مورد وکیل والتر وایت، ساول گودمن و دفتر وکالت او و نحوه آشنایی او با اعضای گروه درست قبل از رخ دادن اتفاقات بریکینگ بد می باشد…",
      image: "/images/posters/walking-dead.jpg",
      Ages: "TV-MA",
      imdb: "8.1",
      like: "79",
      bacImg: "/images/HeroSlider/walking-dead.jpeg",
   },
   {
      title: "The Sopranos",
      des: "استان یک خانواده مافیایی «آنتونی سوپرانو»، رئیس اوباش نیوجرسی می باشد. وی با مسائل حرفه ای و شخصی ای، در خانه و زندگی تجاری خود سروکار دارد که بر وضعیت روحی او تأثیر می گذارد. همین مسائل وی را به مشاوره طلبیدن از یک روانپزشک حرفه ای سوق می دهد.",
      image: "/images/posters/TheSopranos.jpg",
      Ages: "TV-MA",
      imdb: "9.2",
      like: "92",
      bacImg: "/images/HeroSlider/TheSopranos.jpg",
   },

   {
      title: "The Curious Case of Benjamin Button",
      des: "فیلم داستان بنجامین باتون را روایت می کند، مردی که برعکس دیگران، وقتی که تازه به دنیا آمده ظاهری پیر دارد و هرچه از سنش می گذرد جوان‌تر میشود و همین موضوع عواقب عجیب و غریبی برای او در پی دارد.",
      image: "/images/posters/TheCuriousCaseofBenjaminButton.jpg",
      Ages: "PG-13",
      imdb: "7.8",
      like: "70",
      bacImg: "/images/HeroSlider/TheCuriousCaseofBenjaminButton.jpeg",
   },

   {
      title: "Seven",
      des: "قاتلی تصمیم گرفته است هفت نفر را که نماد هفت گناه کبیره هستند به قتل برساند. هدف او از این کار هشدار دادن به انسانهایی است که غرق در گناه روز خود را به شب می رسانند. ",
      image: "/images/posters/seven.jpg",
      Ages: "R",
      imdb: "8.6",
      like: "65",
      bacImg: "/images/HeroSlider/seven.jpg",
   },
];

export default MovieSlider;
